default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: rails_users_authentication
  username: postgres
  password: <%= ENV["RAILS_USER_AUTHENTICATION_DATABASE_PASSWORD"] %>
  host: localhost

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
